[package]
name = "icp_token_wallet"
version = "0.1.0"
authors = ["Sayali Balasaheb Vyavahare <your_email@example.com>"]
edition = "2021"

[dependencies]
ic-cdk = "0.3.0"
ic-cdk-macros = "0.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
